'use client';

import Image from 'next/image';
import Link from 'next/link';
import Navigation from '@/components/Navigation';
import Footer from '@/components/Footer';
import { STATS } from '@/lib/data';
import { ArrowRight, ShieldCheck, MapPin, Sparkles, Heart, Award, CheckCircle } from 'lucide-react';

export default function AboutPage() {
  const milestones = [
    {
      year: '2026',
      title: 'Global Senior Commissions & Flagship Tech',
      desc: 'Executing full-scale visual universes, brand mascot systems, and interactive Next.js flagships for high-growth tech ventures and record labels.'
    },
    {
      year: '2025',
      title: 'Stay Strange 12-Meter Brick Mural',
      desc: 'Commissioned by Cardiff Creative Quarter to paint a massive exterior industrial wall freehand on scaffolding. Surpassed 250k organic social impressions.'
    },
    {
      year: '2024',
      title: '50,000 Unboxing Collector Vinyls & Mascot Systems',
      desc: 'Engineered custom unboxing packaging for Black Screen Records and created the NICE! dev mascot for Game On Digital, lifting onboarding by 64%.'
    },
    {
      year: '2023',
      title: 'Dogs Trust UK Snoopy Public Sculpture',
      desc: 'Selected as premier Welsh artist for "A Dog’s Trail". Hand-painted life-sized fiberglass Snoopy sculpture auctioned for £12,500 for rescue dogs.'
    },
    {
      year: '2022',
      title: 'Solo Gallery Exhibitions & Street Art Residencies',
      desc: 'Gallery showcases in Cardiff, Bristol, and London exploring skate-punk brush lettering, risograph prints, and character counter-culture.'
    }
  ];

  return (
    <main className="min-h-screen bg-white text-black selection:bg-black selection:text-white">
      <Navigation />

      {/* Hero Section */}
      <section className="w-full pt-16 pb-20 px-4 sm:px-6 max-w-[1224px] mx-auto border-b border-black/10">
        <div className="inline-flex items-center gap-2 border-2 border-black rounded-[8px] px-3.5 py-1.5 bg-[#f5f5f5] text-black text-xs font-bold uppercase tracking-wider mb-6 shadow-[2px_2px_0px_0px_#000000]">
          <Sparkles className="w-3.5 h-3.5" />
          <span>01 // The Artist & Creative Technologist</span>
        </div>

        <h1 className="font-display text-4xl sm:text-6xl lg:text-7xl text-black leading-[1.1] mb-6 max-w-4xl">
          From the Drawing Dungeon to Flagship Murals &amp; Production Code.
        </h1>

        <p className="text-lg sm:text-xl text-[#424242] font-light leading-relaxed max-w-3xl mb-8">
          Dharshana is an independent visual artist, commercial illustrator, and creative engineer based in Cardiff, UK. 
          Creating playful pictures, tactile packaging, and category-defining interactive experiences that are bold on your behalf.
        </p>

        <div className="flex flex-wrap items-center gap-4">
          <div className="flex items-center gap-2 text-xs sm:text-sm font-bold border-2 border-black rounded-[8px] px-3.5 py-2 bg-white shadow-[2px_2px_0px_0px_#000000]">
            <MapPin className="w-4 h-4 text-black" />
            <span>Cardiff Bay, Wales, UK (Working Worldwide)</span>
          </div>
          <div className="flex items-center gap-2 text-xs sm:text-sm font-bold border-2 border-black rounded-[8px] px-3.5 py-2 bg-black text-white shadow-[2px_2px_0px_0px_#424242]">
            <ShieldCheck className="w-4 h-4 text-white" />
            <span>100% Solo Principal Execution</span>
          </div>
        </div>
      </section>

      {/* Editorial Bento: Story & Doodles */}
      <section className="w-full py-20 bg-[#fafafa] border-b border-black/10">
        <div className="max-w-[1224px] mx-auto px-4 sm:px-6">
          <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
            {/* Main Narrative Card */}
            <div className="lg:col-span-8 bg-white border-2 border-black rounded-[8px] p-8 sm:p-12 shadow-[6px_6px_0px_0px_#000000]">
              <div className="inline-block border-2 border-black rounded-[8px] px-3 py-1 text-xs font-bold bg-[#f5f5f5] mb-6 shadow-[2px_2px_0px_0px_#000000]">
                PHILOSOPHY & ORIGIN
              </div>

              <h2 className="font-display text-2xl sm:text-4xl text-black mb-6 leading-tight">
                Playful pictures with an unmistakable soul.
              </h2>

              <div className="space-y-5 text-sm sm:text-base text-[#424242] leading-relaxed font-light">
                <p>
                  Most commercial design today suffers from sterile sameness — smoothed-out corporate vectors, safe geometric fonts, and cookie-cutter SaaS layouts that look like they were generated by a committee.
                </p>
                <p>
                  I believe in the power of the hand-drawn mark. From dripping brush-pens on raw sketchbook paper to 12-meter exterior masonry murals in Cardiff&apos;s creative district, my work injects human warmth, irreverence, and memorable attitude into physical spaces and digital products.
                </p>
                <p>
                  Unlike illustrators who stop at the edge of a canvas, I also write production-ready frontend software. I build interactive flagships in Next.js, Framer Motion, and WebGL myself. When you work with me, you don&apos;t get static mockups that get ruined in development — you get a unified artistic and engineering vision delivered to the highest standard.
                </p>
              </div>

              {/* Core Principles */}
              <div className="mt-8 pt-8 border-t-2 border-black/10 grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div className="p-4 rounded-[8px] bg-[#f9f9f9] border-2 border-black">
                  <div className="font-bold text-xs uppercase tracking-wider text-black mb-1">
                    01 // Zero Middlemen
                  </div>
                  <p className="text-xs text-[#424242]">
                    You communicate directly with Dharshana. No account handlers, no junior pass-offs, no dilution of vision.
                  </p>
                </div>
                <div className="p-4 rounded-[8px] bg-[#f9f9f9] border-2 border-black">
                  <div className="font-bold text-xs uppercase tracking-wider text-black mb-1">
                    02 // Full Copyright Buyout
                  </div>
                  <p className="text-xs text-[#424242]">
                    Clear commercial buyout terms. All vector files, high-res masters, and code repositories are 100% yours.
                  </p>
                </div>
              </div>
            </div>

            {/* Side Card: Studio Life & Doodles */}
            <div className="lg:col-span-4 space-y-6">
              {/* Doodles Card */}
              <div className="bg-white border-2 border-black rounded-[8px] p-6 shadow-[4px_4px_0px_0px_#000000] text-center">
                <div className="flex items-center justify-center gap-6 mb-4">
                  <Image
                    src="/images/art-breathe.png"
                    alt="Breathe plant doodle"
                    width={100}
                    height={120}
                    className="w-24 h-auto object-contain hover:scale-105 transition-transform"
                  />
                  <Image
                    src="/images/art-hot-damn.png"
                    alt="Hot damn doodle"
                    width={100}
                    height={120}
                    className="w-24 h-auto object-contain hover:scale-105 transition-transform"
                  />
                </div>
                <div className="font-display text-lg text-black mb-1">
                  Cardiff Drawing Dungeon
                </div>
                <p className="text-xs text-[#7f7f7f]">
                  Where sketchbooks, Posca markers, masonry paint, and Next.js merge.
                </p>
              </div>

              {/* Quick Facts Card */}
              <div className="bg-white border-2 border-black rounded-[8px] p-6 shadow-[4px_4px_0px_0px_#000000]">
                <h3 className="font-bold text-xs uppercase tracking-wider text-black mb-4">
                  Studio Essentials
                </h3>
                <ul className="space-y-2.5 text-xs text-black font-medium">
                  <li className="flex items-center gap-2">
                    <CheckCircle className="w-3.5 h-3.5 text-black" />
                    <span>Based in Cardiff Bay, Wales</span>
                  </li>
                  <li className="flex items-center gap-2">
                    <CheckCircle className="w-3.5 h-3.5 text-black" />
                    <span>Certified Scaffolding & Mural Safety</span>
                  </li>
                  <li className="flex items-center gap-2">
                    <CheckCircle className="w-3.5 h-3.5 text-black" />
                    <span>Next.js & TypeScript Frontend Pro</span>
                  </li>
                  <li className="flex items-center gap-2">
                    <CheckCircle className="w-3.5 h-3.5 text-black" />
                    <span>50K+ Collectibles Shipped Worldwide</span>
                  </li>
                </ul>
              </div>

              {/* Ready CTA Card */}
              <div className="bg-black text-white border-2 border-black rounded-[8px] p-6 shadow-[4px_4px_0px_0px_#424242]">
                <h3 className="font-display text-xl mb-2">
                  Have a Project in Mind?
                </h3>
                <p className="text-xs text-[#bcbcbc] mb-4">
                  Accepting 2 to 3 select commissions per quarter for Q4 / Q1.
                </p>
                <Link
                  href="/contact"
                  className="inline-flex items-center justify-center gap-2 w-full py-2.5 bg-white text-black font-bold text-xs uppercase tracking-wider rounded-[8px] hover:bg-[#f5f5f5] transition-all"
                >
                  <span>Commission Dharshana</span>
                  <ArrowRight className="w-3.5 h-3.5" />
                </Link>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Track Record Stats */}
      <section className="w-full py-20 bg-white border-b border-black/10">
        <div className="max-w-[1224px] mx-auto px-4 sm:px-6">
          <div className="text-center max-w-xl mx-auto mb-12">
            <div className="inline-block border-2 border-black rounded-[8px] px-3 py-1 text-xs font-bold bg-[#f5f5f5] mb-3 shadow-[2px_2px_0px_0px_#000000]">
              VERIFIED RECORD
            </div>
            <h2 className="font-display text-3xl sm:text-4xl text-black">
              Proven Cultural & Commercial Impact.
            </h2>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
            {STATS.map((stat, idx) => (
              <div
                key={stat.label}
                className="bg-white border-2 border-black rounded-[8px] p-6 shadow-[4px_4px_0px_0px_#000000] flex flex-col justify-between"
              >
                <div>
                  <span className="font-mono text-xs font-bold text-[#7f7f7f] block mb-2">
                    // 0{idx + 1} RECORD
                  </span>
                  <div className="font-display text-4xl sm:text-5xl text-black mb-2">
                    {stat.number}
                  </div>
                  <div className="text-base font-bold text-black mb-1">
                    {stat.label}
                  </div>
                </div>
                <div className="text-xs text-[#7f7f7f] pt-4 border-t border-black/10 mt-4 font-light">
                  {stat.note}
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Milestones Timeline */}
      <section className="w-full py-20 bg-[#fafafa] border-b border-black/10">
        <div className="max-w-[1000px] mx-auto px-4 sm:px-6">
          <div className="mb-14 text-center">
            <div className="inline-block border-2 border-black rounded-[8px] px-3 py-1 text-xs font-bold bg-white mb-3 shadow-[2px_2px_0px_0px_#000000]">
              CAREER TIMELINE
            </div>
            <h2 className="font-display text-3xl sm:text-4xl text-black">
              Milestones &amp; Key Works.
            </h2>
          </div>

          <div className="space-y-6">
            {milestones.map((m) => (
              <div
                key={m.year}
                className="bg-white border-2 border-black rounded-[8px] p-6 sm:p-8 shadow-[4px_4px_0px_0px_#000000] flex flex-col sm:flex-row items-start gap-6"
              >
                <div className="font-display text-3xl sm:text-4xl text-black bg-[#f5f5f5] px-4 py-2 rounded-[8px] border-2 border-black shrink-0">
                  {m.year}
                </div>
                <div>
                  <h3 className="font-display text-xl text-black mb-2">
                    {m.title}
                  </h3>
                  <p className="text-sm text-[#424242] leading-relaxed font-light">
                    {m.desc}
                  </p>
                </div>
              </div>
            ))}
          </div>

          {/* Bottom Link to Projects */}
          <div className="text-center mt-12">
            <Link
              href="/project"
              className="inline-flex items-center gap-2 px-8 py-3.5 bg-black text-white text-xs font-bold uppercase tracking-wider rounded-[8px] border-2 border-black shadow-[3px_3px_0px_0px_#424242] hover:bg-[#424242] transition-all cursor-pointer"
            >
              <span>Explore Selected Works</span>
              <ArrowRight className="w-4 h-4" />
            </Link>
          </div>
        </div>
      </section>

      <Footer />
    </main>
  );
}
